In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(3,)

In [ ]:
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [7]:
arr2.shape

(2, 2)

In [8]:
threeD_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(threeD_array)
print(threeD_array.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [9]:
py_list = [1, 2, 3]
print(py_list*2)

[1, 2, 3, 1, 2, 3]


In [10]:
print(py_list +[2])

[1, 2, 3, 2]


In [11]:
np_array = np.array([1, 2, 3])
print(np_array*2)

[2 4 6]
